---
title: "Using embeddings on the census income dataset"
output:
  html_notebook:
editor_options: 
  chunk_output_type: inline
---
  
We've copied some common code for you from the previous notebook so you don't have to start from scratch.

```{r}
library(keras)
library(readr)
library(dplyr)
library(ggplot2)
library(purrr)

use_session_with_seed(7777, disable_gpu = FALSE, disable_parallel_cpu = FALSE)

train_data <- read_csv("data/adult.data",
                       col_names = c("age",
                                     "workclass",
                                     "fnlwgt",
                                     "education",
                                     "education_num",
                                     "marital_status",
                                     "occupation",
                                     "relationship",
                                     "race",
                                     "sex",
                                     "capital_gain",
                                     "capital_loss",
                                     "hours_per_week",
                                     "native_country",
                                     "salary"),
                       col_types = "iciciccccciiicc",
                       na = "?")

train_data <- na.omit(train_data)

y_train <- train_data$salary %>% factor() %>% as.numeric() - 1

x_train <- train_data %>%
  select(-salary) %>%
  mutate_if(is.character, factor)

x_train_continuous <- x_train %>% select_if(is.numeric)
x_train_continuous <- x_train_continuous %>% mutate_all(scale) %>% as.matrix()

x_train_categorical <- x_train %>% select_if(is.factor) 
c(workclass, education, marital_status, occupation, relationship, race, sex, native_country) %<-%
  map(x_train_categorical, compose(to_categorical, as.numeric))
```




```{r}
input_continuous <- layer_input(shape = dim(x_train_continuous)[2]) 
input_workclass <- layer_input(shape = 1)
input_education <- layer_input(shape = 1)
input_marital_status <- layer_input(shape = 1)
input_occupation <- layer_input(shape = 1)
input_relationship <- layer_input(shape = 1)
input_race <- layer_input(shape = 1)
input_sex <- layer_input(shape = 1)
input_native_country <- layer_input(shape = 1)

inputs <- list(input_continuous, input_workclass, input_education, input_marital_status,
               input_occupation, input_relationship, input_race, input_sex, input_native_country)
```



```{r}
dense1 <-
  input_continuous %>% layer_dense(units = 64, activation = "relu") %>%
  layer_dense(units = 64, activation = "relu")
dense2 <-
  input_workclass %>% layer_embedding(
    input_dim = nlevels(x_train_categorical$workclass),
    input_length = 1,
    output_dim = 64,
    name = "workclass_embedding"
  ) %>% layer_flatten() %>%
  layer_dense(units = 64, activation = "relu")
dense3 <-
  input_education %>% layer_embedding(
    input_dim = nlevels(x_train_categorical$education),
    input_length = 1,
    output_dim = 64,
    name = "education_embedding"
  ) %>% layer_flatten() %>%
  layer_dense(units = 64, activation = "relu")
dense4 <-
  input_marital_status %>% layer_embedding(
    input_dim = nlevels(x_train_categorical$marital_status),
    input_length = 1,
    output_dim = 64,
    name = "marital_embedding"
  ) %>% layer_flatten() %>%
  layer_dense(units = 64, activation = "relu")
dense5 <-
  input_occupation %>% layer_embedding(
    input_dim = nlevels(x_train_categorical$occupation),
    input_length = 1,
    output_dim = 64,
    name = "occupation_embedding"
  ) %>% layer_flatten() %>%
  layer_dense(units = 64, activation = "relu")
dense6 <-
  input_relationship %>% layer_embedding(
    input_dim = nlevels(x_train_categorical$relationship),
    input_length = 1,
    output_dim = 64,
    name = "relationship_embedding"
  ) %>% layer_flatten() %>%
  layer_dense(units = 64, activation = "relu")
dense7 <-
  input_race %>% layer_embedding(
    input_dim = nlevels(x_train_categorical$race),
    input_length = 1,
    output_dim = 64,
    name = "race_embedding"
  ) %>% layer_flatten() %>%
  layer_dense(units = 64, activation = "relu")
dense8 <-
  input_sex %>% layer_embedding(
    input_dim = nlevels(x_train_categorical$sex),
    input_length = 1,
    output_dim = 64,
    name = "sex_embedding"
  ) %>% layer_flatten() %>%
  layer_dense(units = 64, activation = "relu")
dense9 <-
  input_native_country %>% layer_embedding(
    input_dim = nlevels(x_train_categorical$native_country),
    input_length = 1,
    output_dim = 64,
    name = "country_embedding"
  ) %>% layer_flatten() %>%
  layer_dense(units = 64, activation = "relu")
```


```{r}
output <- layer_concatenate(list(dense1, dense2, dense3, dense4, dense5, dense6, dense7, dense8, dense9)) %>%
  layer_dropout(rate = 0.5) %>%
  layer_dense(units = 64, activation = "relu") %>%
  layer_dropout(rate = 0.5) %>%
  layer_dense(units = 1, activation = "sigmoid") 
  
model <- keras_model(inputs = inputs, outputs = output)  
model
```


```{r}
model %>% compile(loss = "binary_crossentropy", optimizer = "adam", metrics = "accuracy")
```



```{r}
x_train_categorical_matrix <- x_train_categorical %>%
  mutate_all(as.numeric) %>% 
  mutate_all(function(x) x - 1) %>%
  as.matrix()
```


```{r}
model %>% fit(
  x = list(x_train_continuous, x_train_categorical_matrix[ , 1], x_train_categorical_matrix[ , 2], x_train_categorical_matrix[ , 3], x_train_categorical_matrix[ , 4], x_train_categorical_matrix[ , 5], x_train_categorical_matrix[ , 6], x_train_categorical_matrix[ , 7], x_train_categorical_matrix[ , 8]),
  y = y_train,
  epochs = 20,
  validation_split = 0.2
)
```

