---
title: "Using embeddings on the census income dataset"
output:
  html_notebook:
editor_options: 
  chunk_output_type: inline
---
  
We've copied some common code for you from the previous notebook so you don't have to start from scratch.

```{r}
library(keras)
library(readr)
library(dplyr)
library(ggplot2)
library(purrr)

use_session_with_seed(7777, disable_gpu = FALSE, disable_parallel_cpu = FALSE)

train_data <- read_csv("data/adult.data",
                       col_names = c("age",
                                     "workclass",
                                     "fnlwgt",
                                     "education",
                                     "education_num",
                                     "marital_status",
                                     "occupation",
                                     "relationship",
                                     "race",
                                     "sex",
                                     "capital_gain",
                                     "capital_loss",
                                     "hours_per_week",
                                     "native_country",
                                     "salary"),
                       col_types = "iciciccccciiicc",
                       na = "?")

train_data <- na.omit(train_data)

y_train <- train_data$salary %>% factor() %>% as.numeric() - 1

x_train <- train_data %>%
  select(-salary) %>%
  mutate_if(is.character, factor)

x_train_continuous <- x_train %>% select_if(is.numeric)
x_train_continuous <- x_train_continuous %>% mutate_all(scale) %>% as.matrix()

x_train_categorical <- x_train %>% select_if(is.factor) 
c(workclass, education, marital_status, occupation, relationship, race, sex, native_country) %<-%
  map(x_train_categorical, compose(to_categorical, as.numeric))
```


```{r}
input_continuous <- layer_input(shape = dim(x_train_continuous)[2]) 
input_workclass <- layer_input(shape = 1)
input_education <- layer_input(shape = 1)
input_marital_status <- layer_input(shape = 1)
input_occupation <- layer_input(shape = 1)
input_relationship <- layer_input(shape = 1)
input_race <- layer_input(shape = 1)
input_sex <- layer_input(shape = 1)
input_native_country <- layer_input(shape = 1)

inputs <- list(input_continuous, input_workclass, input_education, input_marital_status,
               input_occupation, input_relationship, input_race, input_sex, input_native_country)
```




