---
title: "Day 2 - TOC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Topics and documents overview

 
 
  

| Slot | Topic                                                      | Slides                     | Notebooks                  | Exercises
| ----:|-----------------------------------------------------------:| --------------------------:| --------------------------:|--------------------------:|
| 1    | Deep learning on tabular data                              | [1_structured_data_slides.Rmd](1_structured_data_slides.Rmd) |[1_structured_data/1_heterogeneous_data_1.Rmd](1_structured_data/1_heterogeneous_data_1.Rmd), [1_structured_data/2_embeddings_so.Rmd](1_structured_data/2_embeddings_so.Rmd), [1_structured_data/3_embeddings_fraud.Rmd](1_structured_data/3_embeddings_fraud.Rmd),  [1_structured_data/4_heterogeneous_data_2.Rmd](1_structured_data/4_heterogeneous_data_2.Rmd)| [1_structured_data/structured_data_quizzes.Rmd](1_structured_data/structured_data_quizzes.Rmd)|
| 2    | Object detection                                           | [2_object_detection_slides.Rmd](2_object_detection_slides.Rmd) | [2_object_detection/1_classification_localization.Rmd](2_object_detection/1_classification_localization.Rmd), [2_object_detection/2_object_detection_ssd.Rmd](2_object_detection/2_object_detection_ssd.Rmd) | [2_object_detection/object_detection_quizzes.Rmd](2_object_detection/object_detection_quizzes.Rmd)|  
| 3    | Time series and sequence-to-sequence learning              | [tbd](day2_slot1/tbd.html) | [tbd](day2_slot1/tbd.html) | [tbd](day2_slot1/tbd.html)|
| 4    | Representation learning, interpretability, and uncertainty | [4_meta_slides.Rmd](4_meta_slides.Rmd) | [4_meta/1_eager_intro.Rmd](4_meta/1_eager_intro.Rmd), [4_meta/2_mmd_cvae.R](4_meta/2_mmd_cvae.R), [4_meta/3_lime.Rmd](4_meta/3_lime.Rmd), [4_meta/4_class_activation_maps.Rmd](4_meta/4_class_activation_maps.Rmd), [4_meta/5_uncertainty_estimates_dropout.Rmd](4_meta/5_uncertainty_estimates_dropout.Rmd) | [4_meta/meta_quizzes.Rmd](4_meta/meta_quizzes.Rmd)|