---
title: "Day 2 - TOC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Topics and documents overview

 
 
  

| Slot | Topic                                                      | Slides                     | Notebooks                  | Exercises
| ----:|-----------------------------------------------------------:| --------------------------:| --------------------------:|--------------------------:|
| 1    | Deep learning on tabular data                              | [1_structureddata_slides.html](day2_slot1/1_structureddata_slides.html) |[embeddings_so.Rmd](day2_slot1/embeddings_so.Rmd), [embeddings_fraud.Rmd](day2_slot1/embeddings_fraud.Rmd), [heterogeneous_data_1.Rmd](day2_slot1/heterogeneous_data_1.Rmd), [heterogeneous_data_2.Rmd](day2_slot1/heterogeneous_data_2.Rmd)| [1_structureddata_quizzes.Rmd](day2_slot1/1_structureddata_quizzes.Rmd)|
| 2    | Object detection                                           | [tbd](day2_slot1/tbd.html) | [tbd](day2_slot1/tbd.html) | [tbd](day2_slot1/tbd.html)|  
| 3    | Time series and sequence-to-sequence learning              | [tbd](day2_slot1/tbd.html) | [tbd](day2_slot1/tbd.html) | [tbd](day2_slot1/tbd.html)|
| 4    | Representation learning, interpretability, and uncertainty | [4_meta_slides.html](day2_slot4/4_meta_slides.html) | [eager_intro.Rmd](day2_slot4/eager_intro.Rmd), [mmd_cvae.R](day2_slot4/mmd_cvae.R), [lime.Rmd](day2_slot4/lime.Rmd), [class_activation_maps.Rmd](day2_slot4/class_activation_maps.Rmd), [uncertainty_estimates_dropout.Rmd](day2_slot4/uncertainty_estimates_dropout.Rmd) | [4_meta_quizzes.Rmd](day2_slot4/4_meta_quizzes.Rmd)|